//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cliente_sw.BDSW {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BDSW.BDSoap")]
    public interface BDSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostrar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/llenar_grid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet llenar_grid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/llenar_grid", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> llenar_gridAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string agregar(string ci, string nom, string carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> agregarAsync(string ci, string nom, string carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string actualizar(string ci, string nom, string carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> actualizarAsync(string ci, string nom, string carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminar(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> eliminarAsync(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscar(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscarAsync(int ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscar1(string b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscar1Async(string b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BDSoapChannel : cliente_sw.BDSW.BDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDSoapClient : System.ServiceModel.ClientBase<cliente_sw.BDSW.BDSoap>, cliente_sw.BDSW.BDSoap {
        
        public BDSoapClient() {
        }
        
        public BDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet mostrar() {
            return base.Channel.mostrar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarAsync() {
            return base.Channel.mostrarAsync();
        }
        
        public System.Data.DataSet llenar_grid() {
            return base.Channel.llenar_grid();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> llenar_gridAsync() {
            return base.Channel.llenar_gridAsync();
        }
        
        public string agregar(string ci, string nom, string carrera) {
            return base.Channel.agregar(ci, nom, carrera);
        }
        
        public System.Threading.Tasks.Task<string> agregarAsync(string ci, string nom, string carrera) {
            return base.Channel.agregarAsync(ci, nom, carrera);
        }
        
        public string actualizar(string ci, string nom, string carrera) {
            return base.Channel.actualizar(ci, nom, carrera);
        }
        
        public System.Threading.Tasks.Task<string> actualizarAsync(string ci, string nom, string carrera) {
            return base.Channel.actualizarAsync(ci, nom, carrera);
        }
        
        public string eliminar(string ci) {
            return base.Channel.eliminar(ci);
        }
        
        public System.Threading.Tasks.Task<string> eliminarAsync(string ci) {
            return base.Channel.eliminarAsync(ci);
        }
        
        public System.Data.DataSet buscar(int ci) {
            return base.Channel.buscar(ci);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscarAsync(int ci) {
            return base.Channel.buscarAsync(ci);
        }
        
        public System.Data.DataSet buscar1(string b) {
            return base.Channel.buscar1(b);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscar1Async(string b) {
            return base.Channel.buscar1Async(b);
        }
    }
}
